### ISSUE TITLE
Problems with 21.4 / path

### ISSUE THREAD

**Issue by BenPrKHS** [opentext/pyxecm#1]
Our installation uses */otcs/cs.exe as basepath.
But the modules always tries */cs/cs

**Comment by kgatz** [comment]
Thanks for the feedback - an option to configure that base_path was implemented today and will be part of the next release in the coming days.

Sample usage:

```python
from pyxecm import OTCS

otcs_object = OTCS(
    protocol="https",
    hostname="otcs.fqdn",
    port="443",
    public_url="https://otcs.fqdn",
    username="admin",
    password="very-secret-value",
    base_path="/OTCS/cs.exe"
)

otcs_object.authenticate()

```

**Comment by BenPrKHS** [comment]
> will be part of the next release

Great, thank you.

**Comment by kgatz** [comment]
Version 1.4.0 has been released.
https://github.com/opentext/pyxecm/releases/tag/v1.4.0
https://pypi.org/project/pyxecm/

With this version we also make the documentation available:
https://opentext.github.io/pyxecm/pyxecm/otcs/#pyxecm.otcs.OTCS.__init__
